baseURL = "https://cassidy.codes"
languageCode = "en-us"
title = "Cassidy K"
theme = "tale"
pygmentsStyle = "monokailight"
pygmentsCodefences = true
enableRobotsTXT = true
canonifyURLs = true
enableRSS = true
enableGitInfo= true
[Author]
  name = "Cassidy K"
[permalinks]
  post = "/blog/:title/"
[params]
  description = "Cassidy K is a Software Engineer in Toronto. She works in Ruby on Rails, Javascript, and anything else she can get her hands on."
  images = ["site-feature-image.jpg"]
  title = "Cassidy K"
[taxonomies]
  series = "series"
